---
- name: Test if cert exists
  stat:
    path: "{{signed_ssh_keyfile}}-cert.pub"
  register: signed_ssh_cert_stat
  check_mode: no
  tags:
    - ssh_signed_hostkeys

- name: Sign certificate
  include_tasks: sign.yml
  when: signed_ssh_cert_stat is defined and not signed_ssh_cert_stat.stat.exists
  vars:
     signed_ssh_certfile: "{{signed_ssh_keyfile}}-cert.pub"
  tags:
    - ssh_signed_hostkeys
