---
- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted
  tags:
    - ssh_signed_hostkeys

- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted
  tags:
    - ssh_signed_hostkeys
